### ISSUE TITLE
ZIP qui marche pas ?

### ISSUE THREAD

**Issue by LinkSkywalker** [alexr4/CC2018-eartsup#1]
J'ai essayé de télécharger le document comportant la nomenclature pour l'exercice, or, Windows ne parvient pas à ouvrir le fichier, et lorsque j'utilise la fonction "Extraire", le système me dit que le dossier est vide.
Quelqu'un d'autre a eu ce souci ?

**Comment by alexr4** [comment]
Je viens de tester le téléchargement du dossier et dezip sur deux machines différentes. Il n'y a aucun problème, le dossier dispose bien de tous les fichiers du cours.

Voici un autre lien direct vers la nomenclature uniquement : [nomenclature.zip](http://arivaux.com/preprod/cc-2018/NOMENCLATURE.zip)
