### ISSUE TITLE
Bug changement affichage points jeu p5js

### ISSUE THREAD

**Issue by TristanCailb** [alexr4/CC2018-eartsup#2]
## Lien
https://github.com/alexr4/CC2018-eartsup/blob/master/Rendu/Game/CAILBOURDIN/JeuP5JS/MyGame.js

## Description

Les points ne se suppriment pas ou ne changent pas de couleur quand le joueur passe dessus alors qu'ils devraient changer

## Comportement désiré
Les points verts devraient se supprimer quand le joueur passe dessus et les points rouges devraient changer de couleur aussi quand le joueur passe dessus

## Comportement actuel
L'affichage des points ne changent pas quand le joueur passe dessus

## Étapes de reproduction
Juste faire passer le joueur sur un point

**Comment by alexr4** [comment]
@TristanCailb je viens de corrigé ton exercice. Le problème d'affichage que tu avais provenait de ta méthode de definition de la couleur. Lorsque tu écris : 
`if(x > 20 || y > 20)
        {
          fill(0, 255, 0);
          noStroke();
          ellipse(x, y, gridRes, gridRes);
          var dist2 = distance(playerX, playerY, x, y);
          if(dist2 < gridRes)
          {
            if(hitsGreen[i][j] == false)
            {
              noFill();
              hitsGreen[i][j] = true;
              score++;
            }
          }
          if(!asRun)
          {
            greenCount++;
          }
        }`

Tu dessine ton ellipse avant de savoir si elle doit être sur scène ou non. Celle-ci est donc déjà sur scène malgré la condition.

Globalement il y avait un problème de logique dans ta fonction showgrid. En effet celle-ci servait à la fois de définition de la grille, de tests dans le jeu et de dessin. Soit trois états différents.

j'ai donc découpé ta fonction en trois éléments distincts : `defineGrid` `updateGrid` et `showGrid`

La première fonction permet de définir la grille de départ et l'état de chaque cellule (green, red ou empty)
La seconde fonction permet de tester si le joueur a touché une cellule selon le modèle suivant : 
Pour chaque cellule
* Si celle-ci n'est pas vide
* * On test la distance entre le joueur et la cellule
* * Si cette distance en inférieur à la distance cherchée
* * * Si la cellule est rouge on retire une vie et redéfinissons la cellule comme vide
* * * Si la cellule est verte on ajoute un point et redéfinissons la cellule comme vide
La troisième méthode permet de dessiner les cellules si celles-ci ne sont pas vide

J'ai mis à jour le github avec la correction [ici](https://github.com/alexr4/CC2018-eartsup/blob/master/Rendu/Game/CAILBOURDIN/JeuP5JS/MyGame_Corrections.js)
